name: TestKP
favicon: null
layout_spectrum: 0.5652147531509399
typography_spectrum: 0.11940001556649804
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#929292'
    - '#dcdcdc'
    - '#262626'
    - '#676767'
    - '#404040'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
